##data dir
graph_dir: '../data/lastfm.mat'
out_dir: './out_lastfm/hopfield_deep'
pretrained: null
out_embedding_file: './bio_embedding_2000_lastfm.txt'

##training
random_seed: 1234
max_epochs: 2000
learning_rate: 0.01
grad_clipping: 10
cuda_id: 0
no_cuda: False

##hopfield
hidden_unit: 2000
layer: 7
beta: 1.5
top_value: 1500
init_beta1: 1
init_beta2: 0.5
top_k: 5
update_rate: 0.2


##debug
save_params: True
logging: True




