##data dir
graph_dir: '../data/POS.mat'
out_dir: './out_pos_2000/hopfield_deep'
#out_dir: null
#pretrained: './out_pos/hopfield_deep'
pretrained: null
out_embedding_file: './bio_embedding_2000_pos.txt'

##training
random_seed: 1234
max_epochs: 100
learning_rate: 0.001
grad_clipping: 10
cuda_id: 0
no_cuda: False

##hopfield
hidden_unit: 2000
layer: 1
#beta: 1.5
init_beta1: 1
init_beta2: 1


##debug
save_params: True
logging: True




